### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by fgallaire** [adafruit/Adafruit_CircuitPython_ATECC#11]
Same issue that:
adafruit/Adafruit_CircuitPython_Thermal_Printer#9
https://github.com/adafruit/Adafruit_CircuitPython_binascii/issues/6

The problem is for SAMD21 non-express boards only.

**Comment by brentru** [comment]
@fgallaire Are you going to be creating a pull request for this issue?

If not, could you please post the error from the CircuitPython REPL so someone can take a look into it? Thanks!
