### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_ATECC#25]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_atecc/adafruit_atecc_asn1.py:41
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:94
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:110
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:129
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:136
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:148
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:160
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:185
- [ ] adafruit_atecc/adafruit_atecc_asn1.py:194
- [ ] adafruit_atecc/adafruit_atecc.py:56
- [ ] adafruit_atecc/adafruit_atecc.py:153
- [ ] adafruit_atecc/adafruit_atecc.py:247
- [ ] adafruit_atecc/adafruit_atecc.py:259
- [ ] adafruit_atecc/adafruit_atecc.py:275
- [ ] adafruit_atecc/adafruit_atecc.py:308
- [ ] adafruit_atecc/adafruit_atecc.py:330
- [ ] adafruit_atecc/adafruit_atecc.py:351
- [ ] adafruit_atecc/adafruit_atecc.py:384
- [ ] adafruit_atecc/adafruit_atecc.py:399
- [ ] adafruit_atecc/adafruit_atecc.py:421
- [ ] adafruit_atecc/adafruit_atecc.py:439
- [ ] adafruit_atecc/adafruit_atecc.py:452
- [ ] adafruit_atecc/adafruit_atecc.py:464
- [ ] adafruit_atecc/adafruit_atecc.py:475
- [ ] adafruit_atecc/adafruit_atecc.py:487
- [ ] adafruit_atecc/adafruit_atecc.py:499
- [ ] adafruit_atecc/adafruit_atecc.py:533
- [ ] adafruit_atecc/adafruit_atecc.py:558
- [ ] adafruit_atecc/adafruit_atecc_cert_util.py:58

**Comment by tekktrik** [comment]
On a related note, it looks like the doc strings need to be updated!  I see a few type errors in the Sphinx params as well as opportunities to use `circuitpython_typing` types!  I was going to address this but not sure I can without importing the module, so doing it at the same time would help.

**Comment by tekktrik** [comment]
Taking this one, I'll do it while I am refactoring this library!

**Comment by brass75** [comment]
Taking this one.
